import './globals.css';

export const metadata = {
 title: 'Create Next App',
 description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    
 return (
  <html lang="en">
   <head>
    <link
     rel="stylesheet"
     href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css"
    />
    <link
     href="https://fonts.googleapis.com/css2?family=Baloo+Da+2:wght@400;500;600;700;800&family=Josefin+Slab:ital,wght@0,400;0,600;1,300;1,400;1,600&family=Muli:ital,wght@0,300;0,400;0,500;1,300;1,400;1,500&display=swap"
     rel="stylesheet"
    />
   </head>

   <body>
    {children}
   </body>
  </html>
 );
}
